# Generated by Django 3.2 on 2021-05-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20201026_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameactivity',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
