# Generated by Django 4.0.1 on 2022-02-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_gameactivity_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourmarker',
            name='platform',
        ),
    ]
